/*
 * SPDX-FileCopyrightText: Copyright (c) 2024 Qorvo US, Inc.
 *
 * SPDX-License-Identifier: LicenseRef-QORVO-1
 */

#pragma once

#include "net/af_ieee802154.h"
#include "net/mcps802154.h"
#include "net/mcps802154_frame.h"
#include "net/mcps802154_schedule.h"
#include "qlist.h"

#define RADAR_TX_PROFILE_IDX_MIN RADAR_TX_PROFILE_HIGH
#define RADAR_TX_PROFILE_IDX_MAX RADAR_TX_PROFILE_LOW

#define RADAR_PREAMBLE_CODE_INDEX_MIN 3
#define RADAR_PREAMBLE_CODE_INDEX_MAX 32

#define RADAR_BURST_PERIOD_MS_MIN 1

#define RADAR_SWEEPS_PER_BURST_MIN 1
#define RADAR_SWEEPS_PER_BURST_MAX 255

#define RADAR_PRIORITY_MIN FIRA_PRIORITY_MIN
#define RADAR_PRIORITY_MAX FIRA_PRIORITY_MAX

#define RADAR_DATA_TYPE_MIN RADAR_DATA_TYPE_SWEEP_SAMPLES
#define RADAR_DATA_TYPE_MAX RADAR_DATA_TYPE_SWEEP_SAMPLES

#define RADAR_ANTENNA_GROUP_NB_MIN 0
#define RADAR_ANTENNA_GROUP_NB_MAX 3

/* TODO(UWB-11190): Change address to an unique value programmed in OTP memory
 */
#define RADAR_IEEE_ADDR 0x8ada88ada88ada88
#define RADAR_FILTER_SHORT_ADDR 0xffff
#define RADAR_FILTER_PAN_ID 0x8aad

#define RADAR_STS_N_SEGS 1
#define RADAR_STS_SEGMENT_LEN 64
#define RADAR_MAC_FRAME_HEADER_LEN \
	(IEEE802154_FC_LEN + IEEE802154_PAN_ID_LEN + IEEE802154_EXTENDED_ADDR_LEN)

#define RADAR_MAC_FRAME_FC_VALUE \
	IEEE802154_FC_MP_VALUE_LONG(IEEE802154_ADDR_LONG, IEEE802154_ADDR_NONE, 1, 0, 1, 0, 0, 0, 0)

#define RADAR_MAC_FRAME_LEN RADAR_MAC_FRAME_HEADER_LEN
